#!/bin/bash
# compute_setup.sh — bootstrap containerized Python compute for ASL-AI.
#
# Builds or locates an Apptainer/Singularity image with nibabel, reportlab,
# matplotlib, and pandas for extract_asl_derivatives.py, compute_asymmetry.py,
# and clinical_report.py.
#
# Usage:
#   ./compute_setup.sh
#
# After running once:
#   source ./compute/env.sh
#   ./run_compute_py.sh clinical_report.py --ai-csv outputs/sub-XXX/stats/*_AI.csv
#
# Image discovery order:
#   1. $ASL_AI_COMPUTE_SIF env var
#   2. ~/Documents/others/containers/asl_ai_compute.sif
#   3. ./compute/asl_ai_compute.sif (pull from Docker Hub or build from container/asl_ai_compute.def)

set -euo pipefail

usage() { sed -n '2,18p' "$0" >&2; exit 2; }
[[ $# -eq 0 ]] || usage

command -v apptainer >/dev/null || command -v singularity >/dev/null || {
  echo "Neither apptainer nor singularity is on PATH" >&2
  exit 3
}
APPTAINER="$(command -v apptainer || command -v singularity)"

repo_dir="$(cd "$(dirname "$0")" && pwd)"
compute_dir="$repo_dir/compute"
mkdir -p "$compute_dir"

candidates=(
  "${ASL_AI_COMPUTE_SIF:-}"
  "$HOME/Documents/others/containers/asl_ai_compute.sif"
  "$compute_dir/asl_ai_compute.sif"
)
sif=""
for c in "${candidates[@]}"; do
  [[ -n "$c" && -f "$c" ]] && { sif="$c"; break; }
done

if [[ -z "$sif" ]]; then
  sif="$compute_dir/asl_ai_compute.sif"
  docker_ref="${ASL_AI_DOCKER_REF:-docker://phindagijimana321/asl-ai-compute:latest}"
  build_tmp="$compute_dir/build-tmp"
  mkdir -p "$build_tmp" "$compute_dir/cache"
  if ! "$APPTAINER" pull "$sif" "$docker_ref"; then
    rm -f "$sif"
    def="$repo_dir/container/asl_ai_compute.def"
    [[ -f "$def" ]] || { echo "Missing Apptainer def: $def" >&2; exit 4; }
    echo "Docker Hub pull failed; building compute image locally (~2–5 min)..."
    echo "  def:   $def"
    echo "  out:   $sif"
    echo "  tmp:   $build_tmp"
    APPTAINER_TMPDIR="$build_tmp" \
    APPTAINER_CACHEDIR="$compute_dir/cache" \
    PROOT_TMP_DIR="$build_tmp" \
    "$APPTAINER" build "$sif" "$def"
  else
    echo "Pulled compute image from $docker_ref"
  fi
fi
echo "Using compute image: $sif"

run_wrapper="$compute_dir/run_in_container.sh"
cat > "$run_wrapper" <<EOF
#!/bin/bash
# Invoke an ASL-AI Python script inside the compute apptainer image.
# Auto-generated by compute_setup.sh
set -euo pipefail
script="\$1"
shift
[[ -f "\$script" ]] || { echo "Script not found: \$script" >&2; exit 4; }
mkdir -p "\${MPLCONFIGDIR:-/tmp/matplotlib-\${USER:-nobody}}"
exec "$APPTAINER" exec \\
  --cleanenv \\
  --env "PYTHONPATH=$repo_dir" \\
  --env "MPLCONFIGDIR=\${MPLCONFIGDIR:-/tmp/matplotlib-\${USER:-nobody}}" \\
  --bind /mnt/nfs \\
  --bind "$repo_dir:$repo_dir" \\
  --bind /tmp \\
  "$sif" \\
  python3 "\$script" "\$@"
EOF
chmod +x "$run_wrapper"

env_sh="$compute_dir/env.sh"
cat > "$env_sh" <<EOF
# Source to prefer the containerized Python compute layer for ASL-AI.
# Generated by compute_setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).

export ASL_AI_COMPUTE_SIF="$sif"
export ASL_AI_COMPUTE_ACTIVE=1

echo "ASL-AI compute (containerized) active."
echo "  Image:  $sif"
echo "  Tools:  extract_asl_derivatives, compute_asymmetry, clinical_report (via run_compute_py.sh)"
EOF

echo
echo "Verifying imports in container..."
"$APPTAINER" exec "$sif" python3 -c \
  "import nibabel, reportlab, matplotlib, pandas, numpy; print('  OK: nibabel reportlab matplotlib pandas numpy')"

echo
echo "Setup complete. To activate in your shell:"
echo "  source $env_sh"
echo
echo "Then run, for example:"
echo "  ./run_compute_py.sh clinical_report.py --ai-csv outputs/sub-URMCPERFII001/stats/sub-URMCPERFII001_acq-singleTI_AI.csv"
